# Generated by Django 4.2.6 on 2025-02-16 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(blank=True, max_length=150, null=True)),
                ('state', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='LocalGovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.TextField(max_length=150)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='locations.state')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.TextField(max_length=150)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area', to='locations.localgovement')),
            ],
        ),
    ]
