# Generated by Django 4.2.6 on 2025-02-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('is_discount', models.BooleanField(default=False)),
                ('is_avaliable', models.BooleanField(default=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
